"""empty message

Revision ID: 49888f74918b
Revises: 00b97b196d0b
Create Date: 2023-11-27 19:19:25.249888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49888f74918b'
down_revision = '00b97b196d0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud_sala', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmacion_alumno', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('confirmacion_tutor', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud_sala', schema=None) as batch_op:
        batch_op.drop_column('confirmacion_tutor')
        batch_op.drop_column('confirmacion_alumno')

    # ### end Alembic commands ###
