"""empty message

Revision ID: 7f5e2b3ff5f7
Revises: 00ef4847a26d
Create Date: 2023-11-30 18:21:17.112333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f5e2b3ff5f7'
down_revision = '00ef4847a26d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salas', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['solicitud_sala_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
