"""empty message

Revision ID: 84503c4f315f
Revises: 53a597af76af
Create Date: 2023-11-30 14:28:14.324110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84503c4f315f'
down_revision = '53a597af76af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.Boolean(), nullable=False))

    with op.batch_alter_table('salas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alumno_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('tutor_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('estado_sala', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('finalizar_alumno', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('finalizar_tutor', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, 'alumnos', ['alumno_id'], ['id'])
        batch_op.create_foreign_key(None, 'tutores', ['tutor_id'], ['id'])

    with op.batch_alter_table('tutores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutores', schema=None) as batch_op:
        batch_op.drop_column('estado')

    with op.batch_alter_table('salas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('finalizar_tutor')
        batch_op.drop_column('finalizar_alumno')
        batch_op.drop_column('estado_sala')
        batch_op.drop_column('tutor_id')
        batch_op.drop_column('alumno_id')

    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.drop_column('estado')

    # ### end Alembic commands ###
