"""empty message

Revision ID: 98ab9c1e8e9a
Revises: 49888f74918b
Create Date: 2023-11-28 15:35:37.937567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98ab9c1e8e9a'
down_revision = '49888f74918b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.drop_constraint('alumnos_password_key', type_='unique')

    with op.batch_alter_table('tutores', schema=None) as batch_op:
        batch_op.drop_constraint('tutores_password_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutores', schema=None) as batch_op:
        batch_op.create_unique_constraint('tutores_password_key', ['password'])

    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.create_unique_constraint('alumnos_password_key', ['password'])

    # ### end Alembic commands ###
