"""empty message

Revision ID: ac702fc8adcc
Revises: 
Create Date: 2023-12-04 12:09:54.960841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac702fc8adcc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alumnos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('apellidos', sa.String(length=120), nullable=False),
    sa.Column('correo_electronico', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('tipo_de_cuenta', sa.Boolean(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo_electronico')
    )
    op.create_table('tutores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('apellidos', sa.String(length=120), nullable=False),
    sa.Column('correo_electronico', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('tipo_de_cuenta', sa.Boolean(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo_electronico')
    )
    op.create_table('cuentas_bancarias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_de_cuenta', sa.Boolean(), nullable=False),
    sa.Column('numero_cuenta', sa.Integer(), nullable=False),
    sa.Column('banco', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_cuenta')
    )
    op.create_table('materias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_materia', sa.String(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_materia')
    )
    op.create_table('metodos_de_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_titular', sa.String(), nullable=False),
    sa.Column('numero_tarjeta', sa.Integer(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Integer(), nullable=False),
    sa.Column('cvv', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cvv'),
    sa.UniqueConstraint('numero_tarjeta')
    )
    op.create_table('perfiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_img', sa.String(length=240), nullable=True),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solicitud_sala',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('confirmacion_alumno', sa.Boolean(), nullable=True),
    sa.Column('confirmacion_tutor', sa.Boolean(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitud_sala_id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('estado_sala', sa.Boolean(), nullable=True),
    sa.Column('finalizar_alumno', sa.Boolean(), nullable=True),
    sa.Column('finalizar_tutor', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.ForeignKeyConstraint(['solicitud_sala_id'], ['solicitud_sala.id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('solicitud_sala_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salas')
    op.drop_table('solicitud_sala')
    op.drop_table('perfiles')
    op.drop_table('metodos_de_pago')
    op.drop_table('materias')
    op.drop_table('cuentas_bancarias')
    op.drop_table('tutores')
    op.drop_table('alumnos')
    # ### end Alembic commands ###
