"""empty message

Revision ID: b6dc17e56498
Revises: 68442516c364
Create Date: 2023-11-21 13:15:46.405671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6dc17e56498'
down_revision = '68442516c364'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitud_sala',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Solicitud_salas')
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_de_cuenta', sa.Boolean(), nullable=True))

    with op.batch_alter_table('cuentas_bancarias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_de_cuenta', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('numero_cuenta', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('banco', sa.ARRAY(sa.String()), nullable=True))
        batch_op.add_column(sa.Column('tutor_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['numero_cuenta'])
        batch_op.create_foreign_key(None, 'tutores', ['tutor_id'], ['id'])

    with op.batch_alter_table('materias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_materia', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('alumno_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('tutor_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('materias_titulo_key', type_='unique')
        batch_op.create_unique_constraint(None, ['nombre_materia'])
        batch_op.create_foreign_key(None, 'tutores', ['tutor_id'], ['id'])
        batch_op.create_foreign_key(None, 'alumnos', ['alumno_id'], ['id'])
        batch_op.drop_column('titulo')

    with op.batch_alter_table('metodos_de_pago', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_titular', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('numero_tarjeta', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('fecha_vencimiento', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('cvv', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('alumno_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['cvv'])
        batch_op.create_unique_constraint(None, ['numero_tarjeta'])
        batch_op.create_foreign_key(None, 'alumnos', ['alumno_id'], ['id'])

    with op.batch_alter_table('perfiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alumno_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('tutor_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'tutores', ['tutor_id'], ['id'])
        batch_op.create_foreign_key(None, 'alumnos', ['alumno_id'], ['id'])

    with op.batch_alter_table('salas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solicitud_sala', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, 'solicitud_sala', ['solicitud_sala'], ['id'])

    with op.batch_alter_table('tutores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_de_cuenta', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutores', schema=None) as batch_op:
        batch_op.drop_column('tipo_de_cuenta')

    with op.batch_alter_table('salas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('solicitud_sala')

    with op.batch_alter_table('perfiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tutor_id')
        batch_op.drop_column('alumno_id')

    with op.batch_alter_table('metodos_de_pago', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('alumno_id')
        batch_op.drop_column('cvv')
        batch_op.drop_column('fecha_vencimiento')
        batch_op.drop_column('numero_tarjeta')
        batch_op.drop_column('nombre_titular')

    with op.batch_alter_table('materias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titulo', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('materias_titulo_key', ['titulo'])
        batch_op.drop_column('tutor_id')
        batch_op.drop_column('alumno_id')
        batch_op.drop_column('nombre_materia')

    with op.batch_alter_table('cuentas_bancarias', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('tutor_id')
        batch_op.drop_column('banco')
        batch_op.drop_column('numero_cuenta')
        batch_op.drop_column('tipo_de_cuenta')

    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.drop_column('tipo_de_cuenta')

    op.create_table('Solicitud_salas',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Solicitud_salas_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Solicitud_salas_pkey')
    )
    op.drop_table('solicitud_sala')
    # ### end Alembic commands ###
