"""empty message

Revision ID: de7d320677d4
Revises: 2dba04044c78
Create Date: 2023-12-08 21:00:54.312274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de7d320677d4'
down_revision = '2dba04044c78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_materia', sa.String(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_materia')
    )
    op.drop_table('materias')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materias',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre_materia', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('alumno_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tutor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], name='materias_alumno_id_fkey'),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutores.id'], name='materias_tutor_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='materias_pkey'),
    sa.UniqueConstraint('nombre_materia', name='materias_nombre_materia_key')
    )
    op.drop_table('categorias')
    # ### end Alembic commands ###
